# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "rsbf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rsbf"
path = "source/main.rs"

[profile.release]
opt-level = 3

[dependencies]
yansi = "0.5.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
